FROM node:20

WORKDIR /home/app

RUN apt-get update && apt-get install -y \
  libvips-dev \
  && rm -rf /var/lib/apt/lists/*

COPY package*.json .env.local ./

# Install only production dependencies
RUN npm cache clean --force
RUN npm install
RUN mv .env.local .env

EXPOSE 8888

CMD ["npm", "run", "start"]
