FROM node:20 AS builder

WORKDIR /home/app

COPY . .

RUN ls -liahS

RUN npm install

RUN npm run build

FROM node:20 AS development

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /home/app

COPY package*.json .env.dev ./

COPY ./public ./public

RUN npm install --only=development \
    && rm -rf /etc/nginx/sites-enabled/asnest-be \
    && mv .env.dev .env \
    && rm -rf ./public/audios/* \
    && rm -rf ./public/images/* \
    && rm -rf ./public/logs/* \
    && rm -rf ./public/raws/* \
    && rm -rf ./public/videos/*

COPY --from=builder /home/app/dist ./dist

COPY .nginx/setup.conf /etc/nginx/conf.d/asnest-be.conf

RUN chmod -R 777 ./public/*
