export enum EVENTS {
	setup = "SET_UP",
	connected = "CONNECTED",
	joinChat = "JOIN_CHAT",
	newMessage = "NEW_MESSAGE",
	messageReceived = "MESSAGE_RECEIVED",
	typing = "TYPING",
	stopTyping = "STOP_TYPING",
	renameChat = "RENAME_CHAT",
	notificationReceived = "NOTIFICATION_RECEIVED",
	error = "ERROR",
	joinCallVideo = "JOIN_CALL_VIDEO",
	leaveCallVideo = "LEAVE_CALL_VIDEO",
	offerCallVideo = "OFFER_CALL_VIDEO",
	answerCallVideo = "ANSWER_CALL_VIDEO",
	iceCandidate = "ICE_CANDIDATE",
	messageVideo = "MESSAGE_VIDEO",
}
